name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

permissions:
  contents: write  # Ensure the workflow has permission to push changes

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Ensures the repo is checked out before making changes

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}  # Ensure this is a classic PAT
          user: NexusGKSoftwares  # Updated to target the NexusGKSoftwares GitHub account
          config_timezone: Europe/Minsk
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_achievements: yes
          plugin_achievements_threshold: X
          plugin_achievements_display: detailed
          plugin_calendar: yes
          plugin_calendar_limit: 11
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_licenses: yes
          plugin_licenses_setup: npm ci
          plugin_skyline: yes
          plugin_skyline_year: 2022
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist
          plugin_support: yes
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A .
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update metrics"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          fi
